version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "./laravel/composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install composer package
          command: composer install -n --prefer-dist
          working_directory: laravel

      - run:
          name: generate .env
          command: cp .env.example .env
          working_directory: laravel

      - run:
          name: genarate key
          command: php artisan key:generate
          working_directory: laravel

      - save_cache:
          key: v1-dependencies-{{ checksum "./laravel/composer.lock" }}
          paths:
            - ./laravel/vendor

      - restore_cache:
          keys:
            - node-v1-{{ checksum "./laravel/package-lock.json" }}
            - node-v1-

      - run:
          name: install npm package
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: laravel

      - save_cache:
          key: node-v1-{{ checksum "./laravel/package-lock.json" }}
          paths:
            - ./laravel/node_modules

      - run:
          name: test php files
          command: ./vendor/bin/phpunit
          working_directory: laravel

      - run:
          name: test vue and js files
          command: npm run test
          working_directory: laravel

      - run:
          name: lint php files
          command: ./laravel/vendor/bin/phpcs .

      - run:
          name: lint vue and js files
          command: ./laravel/node_modules/.bin/eslint ./laravel/resources/js/
